### ISSUE TITLE
Consultation on Dataset Download Issues

### ISSUE THREAD

**Issue by 1083639122** [hust-linyi/insmix#3]
Could you offer a download link for the Kumar dateset?

**Comment by hust-linyi** [comment]
The old link is not available anymore. But this may help you:

https://nucleisegmentationbenchmark.weebly.com/dataset.html

Please cite the original paper if you will use this dataset:

N. Kumar, R. Verma, S. Sharma, S. Bhargava, A. Vahadane and A. Sethi, "[A Dataset and a Technique for Generalized Nuclear Segmentation for Computational Pathology](https://www.dropbox.com/s/j3154xgkkpkri9w/IEEE_TMI_NuceliSegmentation.pdf?dl=0)," in IEEE Transactions on Medical Imaging, vol. 36, no. 7, pp. 1550-1560, July 2017
